var phrases = [
    'I develop in Java',
    'I create stuff',
    'I am a developer',
    'I have a cool community',
    'I am not good at web development',
    '42',
    'I code minecraft mods',
    'I love debugging code',
    'I have a passion for problem-solving',
    'I am always learning something new',
    'I can code circles around my competition',
    'I have a tendency to get lost in my own thoughts...and code',
    'I can turn coffee into code',
    'I am a master of the keyboard',
    'I am constantly improving my skills',
    'I am a coding machine',
    'I am a code wizard',
    'I am a coding ninja',
    'I turn ideas into reality with code',
    'I am a code magician',
    'I am a coding prodigy',
    'I am a coding genius',
    'I am a coding virtuoso',
    'I am a coding savant',
    'I am a coding wizard in training',
    'I am a coding apprentice',
    'I am a coding Jedi (or Sith, depending on your preference)',
    'All of the phrases in this list are generated by an AI (almost)'
];

function typeWriter() {

    var phraseElement = document.getElementById('phrase');
    var txt = phrases[Math.floor(Math.random() * phrases.length)];
    var i = 0;
    var speed = 50;

    function type() {
        if (i < txt.length) {
            phraseElement.textContent += txt.charAt(i);
            i++;
            setTimeout(type, speed);
        } else {
            setTimeout(deletePhrase, 2000);
        }
    }

    function deletePhrase() {
        if (phraseElement.textContent.length > 0) {
            phraseElement.textContent = phraseElement.textContent.substring(0, phraseElement.textContent.length - 1);
            setTimeout(deletePhrase, 50);
        } else {
            typeWriter();
        }
    }

    setTimeout(type, 100);
}

typeWriter();


const currentMonth = new Date().getMonth();

var sound = null;

if (currentMonth === 11) {
    sound = document.getElementById('sound2');
} else {
    sound = document.getElementById('sound');
}

var image = document.getElementsByClassName("pfp")[0];
var modal = document.getElementById("modal");
var slider = document.getElementById("volume-slider");

slider.addEventListener('input', function() {
    sound.volume = slider.value / 100;
});


// Listen for the click event on the image
image.addEventListener("click", function() {
    // Play the sound
    sound.play();
    modal.style.display = "block";
});

modal.addEventListener("click", function(event) {
    // If the user clicks on the modal window, but not on the modal content, close the modal window
    if (event.target === this) {
        this.style.display = "none";
        sound.pause();
    }
});